import Head from 'next/head'

// Components
import Todo from '../components/Todo';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Second Brain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Second Brain</h1>
        <Todo />
      </main>
    </div>
  )
}
