import Head from 'next/head'

// Components
import TaskList from '../components/TaskList';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Second Brain</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='w-screen'>
        <div className=''>
          <TaskList />
        </div>
      </main>
    </div>
  )
}
